FROM tomcat:9.0-jdk17

# Copy custom server.xml
COPY server.xml /usr/local/tomcat/conf/server.xml

# Copy your WAR file
COPY target/demo-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]